### ISSUE TITLE
Clarification on checkpoints used

### ISSUE THREAD

**Issue by ghost** [cvlab-stonybrook/Large-Image-Diffusion#1]
I'm trying to replicate the results of this work and would like clarification on which checkpoints you started from.
Can you please provide that information?

**Comment by AlexGraikos** [comment]
Hello,

For the UNet denoiser we started from the 'cin256-v2' model, provided by the original LDM repo [cin256-v2.yaml](https://huggingface.co/abatecx/stable_diffusion/blob/main/configs/latent-diffusion/cin256-v2.yaml). 
The weights do not seem to be listed at their repo anymore but you should be able to find them [here](https://github.com/cvlab-stonybrook/PathLDM/issues/5).

The VAE we used was the VQ-f4 (https://ommer-lab.com/files/latent-diffusion/vq-f4.zip).

**Comment by jdipalma2** [comment]
@AlexGraikos Great, thanks so much! That's the one I was using but wanted to confirm.
