### ISSUE TITLE
Clarification on Equation (6) Details

### ISSUE THREAD

**Issue by sjjadsa** [cvlab-stonybrook/Large-Image-Diffusion#2]
Thank you for your excellent work on [Repository Name]. I have a few questions regarding the details of Equation (6) from your paper:

1.Details of Equation (6): Could you please provide more details on how Equation (6) is implemented in the code? Specifically, where in the code can I find this implementation?

2.Selection of i and j: How are the indices i and j selected in practice? Is there any overlap between the patches centered at different 
i,j coordinates?

3.Meaning of k and l: What do the indices k and l represent in Equation (6)?

4.How is the inverse mapping performed?

Thank you very much for your assistance!
![01AF95F73FDAAE86C11A3ACA729BF08C](https://github.com/user-attachments/assets/48a539dc-5301-4dd7-a2f7-400898c018b3)

**Comment by srikarym** [comment]
1. You can find the implementation [here](https://github.com/cvlab-stonybrook/Large-Image-Diffusion/blob/7fbb849645509e17ebc17d2f2c127906e77a4674/notebooks/utils.py#L158)
2. We use a stride of 16 pixels in the main paper. Using a smaller stride would require more forward passes, but will result in higher quality images - See Section 14 for more details on this tradeoff.

**Comment by AlexGraikos** [comment]
3. The sum over (k,l) is there to 'average' the contributions from all patches used in denoising the large image. The indices (k,l) use the same stride as (i,j). In our implementation we keep track of the diffusion outputs in the variable `eps_map`, along with the `avg_map`, which counts how many diffusion model outputs are contributing to each pixel. What Eq. (6) describes is that we have to use the `avg_map` to correctly average all of the predictions before we move to the next step in the diffusion process.

4. In the implementation provided the forward mapping is equivalent to selecting a 256x256 patch from the large image -- our diffusion model is trained to denoise 256x256 images. The inverse mapping is placing the output of the diffusion model (which has the same dimensionality as the input) at the location in the large image from which we extracted the patch.
