### ISSUE TITLE
Where can I find these documents?

### ISSUE THREAD

**Issue by hljWmh** [cvlab-stonybrook/Large-Image-Diffusion#3]
from ...models import PriorTransformer, UNet2DConditionModel, UNet2DModel
from ...pipelines import DiffusionPipeline, ImagePipelineOutput
from ...schedulers import UnCLIPScheduler
from ...utils import is_accelerate_available, logging, randn_tensor
from .text_proj import UnCLIPTextProjModel

**Comment by srikarym** [comment]
I assume they are referring to modules in the diffusers repo. They are not required for our repo, and can be commented out.
