### ISSUE TITLE
data enhancement

### ISSUE THREAD

**Issue by hljWmh** [cvlab-stonybrook/Large-Image-Diffusion#4]
I would like to inquire, in the file under hybrid_cond it all mentions data enhancement, I have a question, after already extracting the SSL features, do you still use the original features when doing data enhancement? Does it make sense to do so?

**Comment by AlexGraikos** [comment]
Hello,

If I understand your question correctly you are asking how we perform data augmentation using SSL features and our SSL-conditioned model.

We start with a dataset of images $I$ and labels $L$, $\\{ I_i, L_i \\} $. Then, for that dataset, we also extract the SSL features $C$ for each image constructing $\\{ I_i, L_i, C_i \\} $. Using $C$ and our model we generate new images $I'(C)$ to which we assign the same label as $I$, meaning we now have a new dataset $\\{ I'_i(C_i), L_i \\}$. To train the classifier we use both the original dataset $\\{ I_i, L_i \\}$ and the synthetic data  $\\{ I'_i, L_i \\}$.

The assumption here is that each new image $I'_i$ will have the same label as the original image $I_i$ used in generating it.

Let me know if this clarification helps out.

**Comment by hljWmh** [comment]
Thank you very much for your reply, I have understood it！
