### ISSUE TITLE
synthesis issues

### ISSUE THREAD

**Issue by hljWmh** [cvlab-stonybrook/Large-Image-Diffusion#6]
Hi author, sorry to bother you again. I have a question, the current synthesized image is only a part of the original pathology, right? Or is it the whole pathology image? I saw that the code you wrote mentioned that to synthesize a 1024*1024 pathology image, 16 patches of size 256 are needed. but actually there are many number of patches that can be extracted for the whole pathology slice. If I were to reproduce this task on my own dataset, and my datatype is .svs, would I need to split it into a number of 1024-sized images first, and then go on to the corresponding synthesis task on these 1024 images?

**Comment by AlexGraikos** [comment]
For the large image generation experiments, we trained the models on 256x256 crops from the whole-slide images at 20x magnification.

Training on different-sized crops is possible. You can extract 1024x1024 crops from your slides (.svs files) and train the diffusion model to generate those. A few things you would need to consider are:
- We use an SSL encoder to provide a conditioning vector for every 256x256 crop. The SSL encoders we used were also trained on similarly-sized crops at the same magnification. You may have to use a different SSL encoder or somehow combine multiple SSL embeddings for every generated image.
- The larger the crops the less data you will have. At the scale on which we operated, we ended up with ~12M images to train the diffusion model. If you create larger crops you may have fewer data to train on and end up with a worse model in terms of quality. We observed that the satellite model, which had less data was noticeably worse.

Let me know if you have more questions.

**Comment by hljWmh** [comment]
That is to say, the article was trained by zooming in 20x on the .svs and then cropping to a 256*256 patch. Finally synthesize a number of 1024*1024 sized images according to the positional information of the patches in the original .svs?

**Comment by srikarym** [comment]
You're right about the zooming and crops. 
However, we don't utilize the positional information of the patches in the original .svs to synthesize 1024x1024 images. For more details, please review Sec 3.2 of [our paper](https://arxiv.org/abs/2312.07330).
