### ISSUE TITLE
Results on Patch+Region Embeddings

### ISSUE THREAD

**Issue by jdipalma2** [cvlab-stonybrook/Large-Image-Diffusion#7]
Could you please share your results on Patch+Region experiments like the ones in the config file: https://github.com/cvlab-stonybrook/Large-Image-Diffusion/blob/main/configs/latent-diffusion/brca/only_ssl.yaml

Curious to see how it compares to using only patch embeddings.

**Comment by srikarym** [comment]
Initially, we trained the model with patch and region embedding but observed that the region embedding had no impact during generation. Eventually, we only used patch embedding and passed a zero vector as the region embedding - see [this](https://github.com/cvlab-stonybrook/Large-Image-Diffusion/blob/cf810d0924126a302bbd3403e6b88ae7747781d1/ldm/modules/encoders/modules.py#L36)
